In [1]:
import pandas as pd
from pycaret.regression import *

In [2]:
train = pd.read_csv('./data/train.csv')
test = pd.read_csv('./data/test.csv')

In [3]:
rgn = setup(train, target="SalePrice", ignore_features=["ID"], low_variance_threshold=0.1)
best_model = compare_models(sort='RMSE')

In [7]:
cbr = create_model('catboost', verbose=False)

In [5]:
predict_model(best_model)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,prediction_label
594,595,20,RL,88.0,7990,Pave,NaN,IR1,Lvl,AllPub,...,NaN,MnPrv,NaN,0,4,2008,WD,Normal,110000,114933.333179
1294,1295,20,RL,60.0,8172,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,4,2006,WD,Normal,115000,117130.255836
351,352,120,RL,NaN,5271,Pave,NaN,IR1,Low,AllPub,...,NaN,NaN,NaN,0,12,2006,WD,Abnorml,190000,207460.671948
603,604,160,FV,30.0,3182,Pave,Pave,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,6,2010,WD,Normal,151000,156394.652510
172,173,160,RL,44.0,5306,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,6,2006,WD,Normal,239000,188735.232389
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,406,20,RL,NaN,9991,Pave,NaN,IR1,Lvl,AllPub,...,NaN,GdWo,NaN,0,6,2009,WD,Normal,150000,154890.768216
1201,1202,60,RL,80.0,10400,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,3,2009,WD,Normal,197900,196169.732578
625,626,20,RL,87.0,10000,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,2,2010,WD,Normal,160000,144321.878997
898,899,20,RL,100.0,12919,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,3,2010,New,Partial,611657,468482.046142
668,669,20,RL,NaN,14175,Pave,NaN,Reg,Bnk,AllPub,...,NaN,NaN,NaN,0,11,2006,WD,Normal,168000,173989.983465

In [6]:
final_model = finalize_model(best_model)