In [1]:
import pandas as pd
from pycaret.classification import *

## Data source:
kaggle [link](https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data)

In [2]:
df = pd.read_csv('./breast_cancer_prediction.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

## PyCaret Setup

In [6]:
clf = setup(df, target='diagnosis', ignore_features=['id','Unnamed: 32'])
best_model = compare_models()

In [7]:
lr = create_model('lr')

## Tune Model

In [8]:
tuned_lr = tune_model(lr)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

## Finalize Model

In [12]:
final_model = finalize_model(tuned_lr)

## Make Prediction

In [13]:
# prediction on Validation Set seperated by pycaret
predict_model(final_model)

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,diagnosis,prediction_label,prediction_score
391,8.734,16.840000,55.270000,234.300003,0.10390,0.07428,0.00000,0.00000,0.1985,0.07098,...,317.000000,0.14600,0.13100,0.00000,0.00000,0.2445,0.08865,0,B,0.9980
510,11.740,14.690000,76.309998,426.000000,0.08099,0.09661,0.06726,0.02639,0.1499,0.06758,...,473.799988,0.10730,0.27930,0.26900,0.10560,0.2604,0.09879,0,B,0.9989
475,12.830,15.730000,82.889999,506.899994,0.09040,0.08269,0.05835,0.03078,0.1705,0.05913,...,605.799988,0.13260,0.26100,0.34760,0.09783,0.3006,0.07802,0,B,0.9939
137,11.430,15.390000,73.059998,399.799988,0.09639,0.06889,0.03503,0.02875,0.1734,0.05865,...,462.000000,0.11900,0.16480,0.13990,0.08476,0.2676,0.06765,0,B,0.9982
382,12.050,22.719999,78.750000,447.799988,0.06935,0.10730,0.07943,0.02978,0.1203,0.06659,...,488.399994,0.08799,0.32140,0.29120,0.10920,0.2191,0.09349,0,B,0.9911
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,20.590,21.240000,137.800003,1320.000000,0.10850,0.16440,0.21880,0.11210,0.1848,0.06222,...,1760.000000,0.14640,0.35970,0.51790,0.21130,0.2480,0.08999,1,M,1.0000
377,13.460,28.209999,85.889999,562.099976,0.07517,0.04726,0.01271,0.01117,0.1421,0.05763,...,680.599976,0.11080,0.14570,0.07934,0.05781,0.2694,0.07061,0,B,0.7841
296,10.910,12.350000,69.139999,363.700012,0.08518,0.04721,0.01236,0.01369,0.1449,0.06031,...,392.200012,0.09312,0.07506,0.02884,0.03194,0.2143,0.06643,0,B,1.0000
14,13.730,22.610001,93.599998,578.299988,0.11310,0.22930,0.21280,0.08025,0.2069,0.07682,...,697.700012,0.16510,0.77250,0.69430,0.22080,0.3596,0.14310,1,M,0.8940
5,12.450,15.700000,82.570000,477.100006,0.12780,0.17000,0.15780,0.08089,0.2087,0.07613,...,741.599976,0.17910,0.52490,0.53550,0.17410,0.3985,0.12440,1,M,0.8544